debug: true
server:
  port: 8080
spring:
  application:
    name: moveis_spring_backend
  datasource:
    url: jdbc:h2:file:./target/testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
  flyway:
    url: jdbc:h2:file:./target/testdb
    user: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false